name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  # Запуск по тегу
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set Docker image tag based on event (push or tag)
      - name: Set Docker image tag
        id: docker_tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            # Если сборка запущена по тегу
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            # Если сборка запущена по пушу в ветку main
            SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-8)
            echo "TAG=${SHORT_SHA}" >> $GITHUB_ENV
          fi

      # Log in to GitHub Container Registry (ghcr.io)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64
          tags: |
            ${{ github.repository }}:${{ env.TAG }}
            ${{ github.repository }}:latest